bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_dropout_rate = 0.05
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 20
fp8_base = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
learning_rate = 3e-5
logging_dir = "log"
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 0
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "fp16"
network_alpha = 1
network_args = []
network_dim = 8
network_module = "networks.lora"
network_train_unet_only = true
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW"
output_dir = "C:\\Users\\nin65\\Desktop\\stabledifusion\\lora\\260916_white\\dest01"
output_name = "260916_white"
pretrained_model_name_or_path = "G:/StabilityMatrix/Data/Models/StableDiffusion/boleromixIllustrious_v900.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "C:\\Users\\nin65\\Desktop\\stabledifusion\\lora\\260916_white\\dest01\\sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 5
save_model_as = "safetensors"
save_precision = "fp16"
save_state_on_train_end = true
train_batch_size = 3
train_data_dir = "C:\\Users\\nin65\\Desktop\\stabledifusion\\lora\\260916_white\\src01"
unet_lr = 0.0001
wandb_run_name = "260916_white"
xformers = true
